### ISSUE TITLE
Dismiss all when stacking modals

### ISSUE THREAD

**Issue by jayliu50** [mattjennings/react-modal#1]
Will there be a way to dismiss the whole stack of modals at the same time when the close button is clicked on, rather than popping each and every modal off the stack?

Thank you so much for your work on this lib and sharing it!

**Comment by jayliu50** [comment]
Sorry, I think I have the answer `closeAllModals()`? https://github.com/mattjennings/react-modal-stack

**Comment by mattjennings** [comment]
Yup, `closeAllModals` is the way to do it!
